/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as DocsStreamPayRouteImport } from './routes/docs/stream-pay'
import { Route as PaymentSuccessIndexRouteImport } from './routes/payment/success/index'
import { Route as PaymentFailureIndexRouteImport } from './routes/payment/failure/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsStreamPayRoute = DocsStreamPayRouteImport.update({
  id: '/docs/stream-pay',
  path: '/docs/stream-pay',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessIndexRoute = PaymentSuccessIndexRouteImport.update({
  id: '/payment/success/',
  path: '/payment/success/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailureIndexRoute = PaymentFailureIndexRouteImport.update({
  id: '/payment/failure/',
  path: '/payment/failure/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/stream-pay': typeof DocsStreamPayRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/payment/failure/': typeof PaymentFailureIndexRoute
  '/payment/success/': typeof PaymentSuccessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/stream-pay': typeof DocsStreamPayRoute
  '/checkout': typeof CheckoutIndexRoute
  '/payment/failure': typeof PaymentFailureIndexRoute
  '/payment/success': typeof PaymentSuccessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/stream-pay': typeof DocsStreamPayRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/payment/failure/': typeof PaymentFailureIndexRoute
  '/payment/success/': typeof PaymentSuccessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs/stream-pay'
    | '/checkout/'
    | '/payment/failure/'
    | '/payment/success/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/stream-pay'
    | '/checkout'
    | '/payment/failure'
    | '/payment/success'
  id:
    | '__root__'
    | '/'
    | '/docs/stream-pay'
    | '/checkout/'
    | '/payment/failure/'
    | '/payment/success/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsStreamPayRoute: typeof DocsStreamPayRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  PaymentFailureIndexRoute: typeof PaymentFailureIndexRoute
  PaymentSuccessIndexRoute: typeof PaymentSuccessIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/stream-pay': {
      id: '/docs/stream-pay'
      path: '/docs/stream-pay'
      fullPath: '/docs/stream-pay'
      preLoaderRoute: typeof DocsStreamPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success/': {
      id: '/payment/success/'
      path: '/payment/success'
      fullPath: '/payment/success/'
      preLoaderRoute: typeof PaymentSuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/failure/': {
      id: '/payment/failure/'
      path: '/payment/failure'
      fullPath: '/payment/failure/'
      preLoaderRoute: typeof PaymentFailureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsStreamPayRoute: DocsStreamPayRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  PaymentFailureIndexRoute: PaymentFailureIndexRoute,
  PaymentSuccessIndexRoute: PaymentSuccessIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
